### PR TITLE
SNOW-848733: Run CI builds in parallel

### PR DESCRIPTION
**Pull request by sfc-gh-dprzybysz**
### Description
- Run CI Build jobs in parallel
- Stop old jobs when PR is updated or branch is updated
- PR contains https://github.com/snowflakedb/snowflake-connector-nodejs/pull/551 to not fail on npm audit 

### Checklist
- [x] Format code according to the existing code style (run `npm run lint:check -- CHANGED_FILES` and fix problems in changed code)
- [x] Create tests which fail without the change (if possible)
- [x] Make all tests (unit and integration) pass (`npm run test:unit` and `npm run test:integration`)
- [x] Extend the README / documentation and ensure is properly displayed (if necessary)
- [x] Provide JIRA issue id (if possible) or GitHub issue id in commit message

### CODE REVIEW

**Review by sfc-gh-kdama — APPROVED** [review]
LGTM 👍

**Comment by sfc-gh-igarish** [comment]
What will happen if all tests run on different OS run in parallel and they run on same account, database, schema etc.? Will it cause issues such as one OS drop the table while another really need it?

**Comment by sfc-gh-dprzybysz** [comment]
> What will happen if all tests run on different OS run in parallel and they run on same account, database, schema etc.? Will it cause issues such as one OS drop the table while another really need it?

We are creating unique schema per test run based on runner id and commit sha: https://github.com/snowflakedb/snowflake-connector-nodejs/blob/master/ci/container/test_component.sh#L43

If we don't create/change anything without schema then tests do not influence each other

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Pull request merged**
