### PR TITLE
Fixes issue where callback was not invoked upon network error.

### PR DESCRIPTION
**Pull request by bradleykirwan**
Have kept the TODO in there, in case you want the reminder.

### CODE REVIEW

**Comment by smtakeda** [comment]
@bradleykirwan thanks for PR. Could you elaborate how this change could help to catch the network error?

**Comment by smtakeda** [comment]
ah, ok, I guess I started understanding the intention. By moving, the IF block to under else block, the network error will call the callback?

**Comment by bradleykirwan** [comment]
@smtakeda Yes, currently network errors don't propagate through to the caller. I should really have commented out entire nested IF block, or perhaps remove it altogether.

**Comment by smtakeda** [comment]
working on this.

**Pull request closed without merging**
