### PR TITLE
Workaround for SNOW-143538

### PR DESCRIPTION
**Pull request by Ginden**
SNOW-143538
#85

### CODE REVIEW

**Comment by snowstakeda** [comment]
@Ginden, Thanks for PR. did you have a chance to verify this fix worked?

**Comment by Ginden** [comment]
@snowstakeda It reduced our problems with failing long-running queries.

**Comment by snowstakeda** [comment]
thanks. we'll push this change to the next release.

**Comment by snowstakeda** [comment]
Merged to #96

**Pull request closed without merging**
