### PR TITLE
Bump dependencies - https-proxy-agent & agent-base

### LINKED ISSUE #234: "got" package ability to make http(s)-requests is broken after the call snowflake.createConnection
1. What version of NodeJS are you using (`node --version` and `npm --version`)?
Nove version: v12.22.4
npm version: 6.14.11

2. What operating system and processor architecture are you using?

Windows: Windows 10 Pro
Version: 10.0.19044 build 19044

3. What are the component versions in the environment (`npm list`)?
got: 11.8.3
snowflake-sdk: 1.6.5
typescript: 4.4.2

4. What did you do?
```
import snowflake, { Connection } from 'snowflake-sdk';
import got from 'got';

const conn = snowflake.createConnection({
            account: '',
            username: '',
            password: '',
            warehouse: '',
            database: '',
            schema: '',
            authenticator: 'SNOWFLAKE'
    });
const res = await got.get('https://www.google.com');
```
5. What did you expect to see?

HTTP 200 response with HTML in a response body

6. What did you see instead?

Error:
  "name": "RequestError",
  "code": "ECONNREFUSED",
   "message": connect ECONNREFUSED 127.0.0.1:443
stacktrace:
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (<project_path>\node_modules\got\dist\source\core\index.js:962:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at ClientRequest.origin.emit (<project_path>\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14)

7. Add this to get standard output.
 
```
var snowflake = require('./snowflake');
snowflake.configure(
{
  logLevel: 'trace'
});
```
No trace messages in the console

### PR DESCRIPTION
**Pull request by mrollinsiv**
Resolves #234

After importing `snowflake-sdk` all HTTPS requests from `got` result in `connect ECONNREFUSED 127.0.0.1:443` errors.

`https-proxy-agent` to `^5.0.0`
`agent-base` to `^6.0.0`

### CODE REVIEW

**Comment by joelfillmore** [comment]
Should resolve #201 as well.

**Comment by gondar00** [comment]
I think you need to commit the `package-lock.json` as well @mrollinsiv

**Comment by mrollinsiv** [comment]
> I think you need to commit the `package-lock.json` as well @mrollinsiv

The lock file is listed in `.gitignore` for this repo

**Comment by dylangrandmont** [comment]
> The lock file is listed in .gitignore for this repo

Is this intended? Normally lock files are meant to be committed to source code so every contributor resolves the dependency tree deterministically. https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

**Comment by askn** [comment]
Is there any update on this?

**Comment by Navaneeth-pk** [comment]
Home someone will take a look at this PR soon. Have been waiting since December.

**Comment by ahungry** [comment]
Anyone maintain this repo?

This is a ridiculous problem - no package deps should be pulled in that mess with core BIF / modules.

**Comment by mrollinsiv** [comment]
> Anyone maintain this repo?
> 
> This is a ridiculous problem - no package deps should be pulled in that mess with core BIF / modules.

Agree, there are also a few dependencies that should just be devDependencies. 

Is there a maintainer that can look at this PR?

**Comment by mrollinsiv** [comment]
Bumps were handled in #274

**Pull request closed without merging**
