### PR TITLE
avoid then to allow sync authenticate methods

### PR DESCRIPTION
**Pull request by safareli**
fix: https://github.com/snowflakedb/snowflake-connector-nodejs/issues/308
alternative of : https://github.com/snowflakedb/snowflake-connector-nodejs/pull/310/

### CODE REVIEW

**Comment by safareli** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by safareli** [comment]
recheck

**Review by itsknob — APPROVED** [review]

**Comment by itsknob** [comment]
I've ended up making the same changes while debugging through this locally. Since this is using await, there should be no need for the `.then()` chaining.

**Comment by sfc-gh-dprzybysz** [comment]
It was fixed in https://github.com/snowflakedb/snowflake-connector-nodejs/pull/522

**Pull request closed without merging**
