### PR TITLE
Override node-fetch version of @azure/storage-blob to 3.2.10

### PR DESCRIPTION
**Pull request by SimbaGithub**
Based off SF# 00402210 and snyk issue https://github.com/snowflakedb/snowflake-connector-nodejs/issues/334

The @azure/storage-blob package uses node-fetch as a dependency. Override node-fetch to 3.2.10 to fix the vulnerability

### CODE REVIEW

**Comment by SimbaGithub** [comment]
Test failures on Windows are unrelated to code changes
The release PR had similar test failures: https://github.com/snowflakedb/snowflake-connector-nodejs/pull/344

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Comment by sfc-gh-igarish** [comment]
Please check test failure before the merge.

**Comment by SimbaGithub** [comment]
> Please check test failure before the merge.

Test failures are unrelated to code changes: https://github.com/snowflakedb/snowflake-connector-nodejs/pull/344

**Pull request merged**
