### PR TITLE
Updated axios version to 1.6.0

### PR DESCRIPTION
**Pull request by codetycon**
Updated axios version to 1.6.0

### Description
Updated axios version from 1.5.1 to 1.6.0  

### Checklist
- [x] Format code according to the existing code style (run `npm run lint:check -- CHANGED_FILES` and fix problems in changed code)
- [x] Create tests which fail without the change (if possible)
- [x] Make all tests (unit and integration) pass (`npm run test:unit` and `npm run test:integration`)
- [x] Extend the README / documentation and ensure is properly displayed (if necessary)
- [x] Provide JIRA issue id (if possible) or GitHub issue id in commit message

### CODE REVIEW

**Comment by codetycon** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by codetycon** [comment]
recheck

**Comment by codetycon** [comment]
recheck

**Review by sfc-gh-pbulawa — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
