### PR TITLE
update Readme.md to suggest raising cases with Support for production issues

### PR DESCRIPTION
**Pull request by sfc-gh-dszmolka**

### CODE REVIEW

**Review by sfc-gh-igarish — APPROVED** [review]
LGTM

**Comment by sfc-gh-dszmolka** [comment]
cheers @sfc-gh-igarish for reviewing so quickly! sadly i don't seem to have write access here which is necessary for self-merge the PR.  can you perhaps merge it too please ?

**Comment by sfc-gh-igarish** [comment]
@sfc-gh-dszmolka Still required merge gates is not passing. I know it's only README changes. But because required merge gate is still pending, it's not allowing me to merge.

**Comment by sfc-gh-dszmolka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sfc-gh-dszmolka** [comment]
recheck

**Comment by sfc-gh-dszmolka** [comment]
recheck

**Comment by sfc-gh-igarish** [comment]
Ping KIran to look into Windows build issue.

**Comment by sfc-gh-kdama** [comment]
Opened https://github.com/snowflakedb/snowflake-connector-nodejs/pull/406

**Pull request closed without merging**
