### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by htunnicliff**

### CODE REVIEW

**Comment by htunnicliff** [comment]
@sfc-gh-stakeda I recently submitted this pull request in order to add a TypeScript declaration file to this library. Having a declaration file bundled with your library would enable advanced code intelligence/auto-completion within developer IDEs.

**Comment by sfc-gh-stakeda** [comment]
Thanks for PR, @htunnicliff . Currently the code ownership is in transition to a new owner. We'll have them take care of this PR. Thanks.

**Comment by htunnicliff** [comment]
Any updates here? This should be a really painless merge and package update.

**Comment by htunnicliff** [comment]
> Any updates here? This should be a really painless merge and package update.

@sfc-gh-abhatnagar

**Comment by htunnicliff** [comment]
Hi @sfc-gh-abhatnagar , @sfc-gh-kwagner, @sfc-gh-hchaturvedi – Can you please merge this PR or comment with the necessary changes?

**Comment by htunnicliff** [comment]
I will be adding types to the Definitely Typed repository instead.

**Comment by htunnicliff** [comment]
Types for this package have been added to Definitely Typed and are installable by running
```
npm install —save-dev @types/snowflake-sdk
```

Future edits to the types must be made in Definitely Typed (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/snowflake-sdk/index.d.ts)

**Pull request closed without merging**
